model: 'long_rcnn_det'
network: 'rcnn_34'
task: 'ct_rcnn'
resume: true
gpus: (0,)

train:
    optim: 'adam'
    lr: 1e-4
    milestones: (25, 50)
    gamma: 0.5
    batch_size: 1
    dataset: 'CocoTrain'
    num_workers: 8
    epoch: 50
test:
    dataset: 'CocoVal'
    batch_size: 1

heads: {'act_hm': 8, 'awh': 2}
segm_or_bbox: 'bbox'
ct_score: 0.03
