model: 'coco'
network: 'ro_34'     # Syntax: arch_numOfLayers
task: 'snake' # Determines which network to call
resume: true
gpus: (0,) # Must be a tuple

train:
    optim: 'adam'
    lr: 0.001
    milestones: (6,12,18,24)
    gamma: 0.5
    batch_size: 16
    dataset: 'eoeTrain' # Change this to your dataset
    num_workers: 0
    epoch: 30
    weight_decay: 0.001
use_val: true
val:
    dataset: 'eoeVal'
    batch_size: 1
test:
    dataset: 'eoeTest' # Change this to your dataset
    batch_size: 1

heads: {'ct_hm': 4, 'wh': 2, 'reg': 2}
segm_or_bbox: 'segm'
ct_score: 0.3
save_ep: 1
eval_ep: 1
# debug_test: true
# save_images: true
dice: true
rotate_reproduce: true
rotate: 90