model: 'coco'
network: 'ro_34'     # Syntax: arch_numOfLayers
task: 'circle_snake' # Determines which network to call
resume: false
# pretrain: 'ctdet_coco_dla_2x.pth'
gpus: (0,) # Must be a tuple

train:
    optim: 'adam'
    lr: 0.0001
    # milestones: (40,50)
    gamma: 0.5
    batch_size: 4
    dataset: 'eoeTrain' 
    num_workers: 0
    epoch: 40
    # weight_decay: 0.001
use_val: true
val:
    dataset: 'eoeVal'
    batch_size: 1
test:
    dataset: 'eoeTest' 
    batch_size: 1

heads: {'ct_hm': 4, 'radius': 1, 'reg': 2}
segm_or_bbox: 'both'
ct_score: 0.05
save_ep: 1
eval_ep: 1
# debug_test: true
# save_images: true
dice: true
# rotate_reproduce: true
# rotate: 90
