model: 'coco'
network: 'ro_34'
task: 'circle_snake'
resume: true

gpus: (0,)

train:
    optim: 'sgd'
    lr: 0.01
    milestones: (6,12,18,24)
    gamma: 0.5
    batch_size: 4
    dataset: 'kidpathTrain'
    num_workers: 0
    epoch: 50
    weight_decay: 0.001
use_val: true
val:
    dataset: 'kidpathVal'
    batch_size: 1
test:
    dataset: 'kidpathTest'
    batch_size: 1

heads: {'ct_hm': 1, 'radius': 1, 'reg': 2}
segm_or_bbox: 'both'
ct_score: 0.3
save_ep: 1
eval_ep: 1

# debug_test: true
# save_images: true
dice: true

rotate_reproduce: true
rotate: 90