model: 'coco'
network: 'ro_34'
task: 'snake'
resume: true
gpus: (0)

train:
    optim: 'adam'
    lr: 1e-4
    milestones: (80, 120, 150, 170)
    gamma: 0.5
    batch_size: 3
    dataset: 'CocoTrain'
    num_workers: 8
    epoch: 200
test:
    dataset: 'CocoMini'
    batch_size: 1

heads: {'ct_hm': 1, 'wh': 2, 'reg': 2}
segm_or_bbox: 'segm'
